[package]
name = "rvm"
version = "0.1.0"
authors = ["equation314 <equation618@gmail.com>", "chenyu <believe.chenyu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = "0.5"
bitflags = "1.2"
bit-set = { version = "0.5", default-features = false }
x86_64 = { git = "https://github.com/equation314/x86_64", rev = "4ad4551" }
