name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Check code format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: rust-src
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-features
    - name: Build examples
      run: cd examples/uefi && make build
    - name: Build docs
      uses: actions-rs/cargo@v1
      with:
        command: doc
